using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyCompanyAttribute("Monastry")]
[assembly: AssemblyVersionAttribute("0.0.0.3")]
[assembly: AssemblyFileVersionAttribute("0.0.0.3")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0.bb2ae1c9fed7")]
[assembly: AssemblyTitleAttribute("Monastry.ActiveRecord")]
[assembly: AssemblyProductAttribute("Monastry.ActiveRecord")]
[assembly: AssemblyDescriptionAttribute("Monastry.ActiveRecord is a product of Monastry - https://monastry-activerecord.go" +
    "oglecode.com/hg/.")]
[assembly: AssemblyTrademarkAttribute("Monastry.ActiveRecord - Monastry")]
[assembly: AssemblyCopyrightAttribute("Copyright 2011 Monastry, - Original author or authors")]

