using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.239
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyCompanyAttribute("Monastry")]
[assembly: AssemblyVersionAttribute("4.0.0.14")]
[assembly: AssemblyFileVersionAttribute("4.0.0.14")]
[assembly: AssemblyInformationalVersionAttribute("4.0.0.0097727c11e53839fe6cb1275a677b30d24b85a7")]
[assembly: AssemblyTitleAttribute("Monastry.ActiveRecord")]
[assembly: AssemblyProductAttribute("Monastry.ActiveRecord")]
[assembly: AssemblyDescriptionAttribute("Monastry.ActiveRecord is a product of Monastry - https://mzywitza@github.com/mzyw" +
    "itza/Monastry.ActiveRecord.git.")]
[assembly: AssemblyTrademarkAttribute("Monastry.ActiveRecord - Monastry")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2011 Monastry, - Original author or authors")]

